# Generated by Django 4.1.7 on 2023-02-15 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddcbackend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asrdata',
            name='audiopath',
        ),
        migrations.RemoveField(
            model_name='asrdata',
            name='user',
        ),
        migrations.CreateModel(
            name='AudioData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audiopath', models.CharField(max_length=250)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ddcbackend.userdata')),
            ],
        ),
    ]
