# Generated by Django 4.1.7 on 2023-02-15 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddcbackend', '0002_remove_asrdata_audiopath_remove_asrdata_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiodata',
            name='transcription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ddcbackend.asrdata'),
        ),
    ]
