# Generated by Django 4.1.7 on 2023-04-05 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ddcbackend', '0005_remove_userdata_name_userdata_phonenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='phonenumber',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='UserAsrData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('transcription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddcbackend.asrdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
