# Generated by Django 4.1.7 on 2023-05-01 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddcbackend', '0006_alter_userdata_phonenumber_userasrdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentationpost',
            name='html_content',
        ),
    ]
