# Generated by Django 4.1.7 on 2023-05-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddcbackend', '0007_remove_documentationpost_html_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiodata',
            name='processedaudio',
            field=models.BooleanField(default=False),
        ),
    ]
