# Generated by Django 4.1.7 on 2023-05-04 02:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ddcbackend', '0008_audiodata_processedaudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiodata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
